version: '3.8'

services:
  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - eureka-network

  product-service:
    build: ./product-service
    ports:
      - "8081:8081"
    depends_on:
      eureka-server:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICE-URL_DEFAULT-ZONE=http://eureka-server:8761/eureka/
      - SERVER_PORT=8081
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/products/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - eureka-network

  inventory-service-1:
    build: ./inventory-service
    ports:
      - "8082:8082"
    depends_on:
      eureka-server:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICE-URL_DEFAULT-ZONE=http://eureka-server:8761/eureka/
      - SERVER_PORT=8082
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/inventory/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - eureka-network

  inventory-service-2:
    build: ./inventory-service
    ports:
      - "8083:8083"
    depends_on:
      eureka-server:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICE-URL_DEFAULT-ZONE=http://eureka-server:8761/eureka/
      - SERVER_PORT=8083
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/inventory/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - eureka-network

networks:
  eureka-network:
    driver: bridge